// <auto-generated />
using FilmDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmDB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251124101029_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilmDB.Models.Database.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("character_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.HasKey("CharacterId");

                    b.HasIndex("Name");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("FilmDB.Models.Database.Film", b =>
                {
                    b.Property<string>("FilmId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("film_id");

                    b.Property<int>("GenreBitField")
                        .HasColumnType("int")
                        .HasColumnName("genre_bit_field");

                    b.Property<short>("RunTimeMinutes")
                        .HasColumnType("smallint")
                        .HasColumnName("run_time_minutes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("title");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("FilmId");

                    b.HasIndex("GenreBitField");

                    b.HasIndex("Title");

                    b.HasIndex("Year");

                    b.ToTable("Film");
                });

            modelBuilder.Entity("FilmDB.Models.Database.FilmGenre", b =>
                {
                    b.Property<int>("FilmGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("film_genre_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmGenreId"));

                    b.Property<string>("FilmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("film_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasColumnName("genre_id");

                    b.HasKey("FilmGenreId");

                    b.HasIndex("FilmId");

                    b.HasIndex("GenreId");

                    b.ToTable("Film_Genre");
                });

            modelBuilder.Entity("FilmDB.Models.Database.FilmPerson", b =>
                {
                    b.Property<string>("FilmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("film_id");

                    b.Property<byte>("JobId")
                        .HasColumnType("tinyint")
                        .HasColumnName("job_id");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("person_id");

                    b.HasIndex("FilmId");

                    b.HasIndex("JobId");

                    b.HasIndex("PersonId");

                    b.ToTable("Film_Person");
                });

            modelBuilder.Entity("FilmDB.Models.Database.FilmPersonCharacter", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("character_id");

                    b.Property<string>("FilmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("film_id");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("person_id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("FilmId", "PersonId");

                    b.ToTable("Film_Person_Character");
                });

            modelBuilder.Entity("FilmDB.Models.Database.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("genre_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("GenreId");

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("FilmDB.Models.Database.Job", b =>
                {
                    b.Property<byte>("JobId")
                        .HasColumnType("tinyint")
                        .HasColumnName("job_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("JobId");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("FilmDB.Models.Database.Person", b =>
                {
                    b.Property<string>("PersonId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("person_id");

                    b.Property<short?>("BirthYear")
                        .HasColumnType("smallint")
                        .HasColumnName("birth_year");

                    b.Property<short?>("DeathYear")
                        .HasColumnType("smallint")
                        .HasColumnName("death_year");

                    b.Property<string>("FirstFilmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_film_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.HasKey("PersonId");

                    b.HasIndex("Name");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("FilmDB.Models.Database.PersonJobSummary", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("job_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<short>("EarliestYear")
                        .HasColumnType("smallint")
                        .HasColumnName("earliest_year");

                    b.Property<int>("JobCount")
                        .HasColumnType("int")
                        .HasColumnName("job_count");

                    b.Property<short>("LatestYear")
                        .HasColumnType("smallint")
                        .HasColumnName("latest_year");

                    b.Property<string>("PersonId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("JobId");

                    b.HasIndex("PersonId");

                    b.ToTable("Person_Job_Summary");
                });

            modelBuilder.Entity("FilmDB.Models.Database.PersonJobSummary", b =>
                {
                    b.HasOne("FilmDB.Models.Database.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
